name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  pipeline: 
    runs-on: [windows-latest, macos-latest, ubuntu-latest]
    strategy: 
      matrix: 
        node-version: [ 16.x ]

    steps: 
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build producion project
        run: npm run build:prod
      - name: linting typescript
        run: npm run lint:ts
      - name: linting styles
        run: npm run lint:sccs
      - name: unit testing
        run: npm run test:unit
